//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_VT18.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog_VT18.App_LocalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new category.
        /// </summary>
        public static string BtnCreateCategory {
            get {
                return ResourceManager.GetString("BtnCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string BtnLogIn {
            get {
                return ResourceManager.GetString("BtnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string BtnRegister {
            get {
                return ResourceManager.GetString("BtnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Answer.
        /// </summary>
        public static string BtnSendAnswer {
            get {
                return ResourceManager.GetString("BtnSendAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string LblAbout {
            get {
                return ResourceManager.GetString("LblAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string LblAccepted {
            get {
                return ResourceManager.GetString("LblAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted meetings.
        /// </summary>
        public static string LblAcceptedMeetings {
            get {
                return ResourceManager.GetString("LblAcceptedMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new blogpost.
        /// </summary>
        public static string LblAdd {
            get {
                return ResourceManager.GetString("LblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string LblAllTimeSugges {
            get {
                return ResourceManager.GetString("LblAllTimeSugges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string LblBlog {
            get {
                return ResourceManager.GetString("LblBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogpost.
        /// </summary>
        public static string LblBlogPost {
            get {
                return ResourceManager.GetString("LblBlogPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string LblCalendar {
            get {
                return ResourceManager.GetString("LblCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LblCancel {
            get {
                return ResourceManager.GetString("LblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LblCategory {
            get {
                return ResourceManager.GetString("LblCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string LblContact {
            get {
                return ResourceManager.GetString("LblContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string LblContent {
            get {
                return ResourceManager.GetString("LblContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string LblCreate {
            get {
                return ResourceManager.GetString("LblCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new account.
        /// </summary>
        public static string LblCreateNewAccount {
            get {
                return ResourceManager.GetString("LblCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new event.
        /// </summary>
        public static string LblCreateNewEvent {
            get {
                return ResourceManager.GetString("LblCreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LblDate {
            get {
                return ResourceManager.GetString("LblDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string LblDay {
            get {
                return ResourceManager.GetString("LblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LblEdit {
            get {
                return ResourceManager.GetString("LblEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string LblEducation {
            get {
                return ResourceManager.GetString("LblEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string LblEndDate {
            get {
                return ResourceManager.GetString("LblEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string LblFrom {
            get {
                return ResourceManager.GetString("LblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string LblHide {
            get {
                return ResourceManager.GetString("LblHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can find important information about system development here..
        /// </summary>
        public static string LblInfo {
            get {
                return ResourceManager.GetString("LblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informal.
        /// </summary>
        public static string LblInformal {
            get {
                return ResourceManager.GetString("LblInformal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instution Blog.
        /// </summary>
        public static string LblInstutionBlog {
            get {
                return ResourceManager.GetString("LblInstutionBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal blog.
        /// </summary>
        public static string LblInternalBlog {
            get {
                return ResourceManager.GetString("LblInternalBlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invited.
        /// </summary>
        public static string LblInvited {
            get {
                return ResourceManager.GetString("LblInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about oru.
        /// </summary>
        public static string LblLearnMore {
            get {
                return ResourceManager.GetString("LblLearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LblLogIn {
            get {
                return ResourceManager.GetString("LblLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LblLogOff {
            get {
                return ResourceManager.GetString("LblLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting suggestions.
        /// </summary>
        public static string LblMeetingSugges {
            get {
                return ResourceManager.GetString("LblMeetingSugges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting text.
        /// </summary>
        public static string LblMeetingText {
            get {
                return ResourceManager.GetString("LblMeetingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string LblMonth {
            get {
                return ResourceManager.GetString("LblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Event.
        /// </summary>
        public static string LblNewEvent {
            get {
                return ResourceManager.GetString("LblNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open blogpost.
        /// </summary>
        public static string LblOpenPost {
            get {
                return ResourceManager.GetString("LblOpenPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending meetings.
        /// </summary>
        public static string LblPendingMeetings {
            get {
                return ResourceManager.GetString("LblPendingMeetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LblRegister {
            get {
                return ResourceManager.GetString("LblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string LblRememberMe {
            get {
                return ResourceManager.GetString("LblRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research.
        /// </summary>
        public static string LblResearch {
            get {
                return ResourceManager.GetString("LblResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LblSave {
            get {
                return ResourceManager.GetString("LblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string LblSender {
            get {
                return ResourceManager.GetString("LblSender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send event suggestions.
        /// </summary>
        public static string LblSendEventSugges {
            get {
                return ResourceManager.GetString("LblSendEventSugges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string LblShow {
            get {
                return ResourceManager.GetString("LblShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string LblStartDate {
            get {
                return ResourceManager.GetString("LblStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestions.
        /// </summary>
        public static string LblSugges {
            get {
                return ResourceManager.GetString("LblSugges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string LblToday {
            get {
                return ResourceManager.GetString("LblToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View blogpost.
        /// </summary>
        public static string LblViewBlogPost {
            get {
                return ResourceManager.GetString("LblViewBlogPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string LblWeek {
            get {
                return ResourceManager.GetString("LblWeek", resourceCulture);
            }
        }
    }
}
