//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_VT18.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog_VT18.App_LocalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa nytt inlägg.
        /// </summary>
        public static string LblAdd {
            get {
                return ResourceManager.GetString("LblAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avsluta.
        /// </summary>
        public static string LblCancel {
            get {
                return ResourceManager.GetString("LblCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta lösenord.
        /// </summary>
        public static string LblConfirmPassword {
            get {
                return ResourceManager.GetString("LblConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innehåll.
        /// </summary>
        public static string LblContent {
            get {
                return ResourceManager.GetString("LblContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny kategori.
        /// </summary>
        public static string LblCreateCategory {
            get {
                return ResourceManager.GetString("LblCreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skapa ny användare.
        /// </summary>
        public static string LblCreateNewAccount {
            get {
                return ResourceManager.GetString("LblCreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dag.
        /// </summary>
        public static string LblDay {
            get {
                return ResourceManager.GetString("LblDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utbildning.
        /// </summary>
        public static string LblEducation {
            get {
                return ResourceManager.GetString("LblEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LblEmail {
            get {
                return ResourceManager.GetString("LblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från.
        /// </summary>
        public static string LblFrom {
            get {
                return ResourceManager.GetString("LblFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dölj.
        /// </summary>
        public static string LblHide {
            get {
                return ResourceManager.GetString("LblHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informell.
        /// </summary>
        public static string LblInformal {
            get {
                return ResourceManager.GetString("LblInformal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogg.
        /// </summary>
        public static string LblListPost {
            get {
                return ResourceManager.GetString("LblListPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Månad.
        /// </summary>
        public static string LblMonth {
            get {
                return ResourceManager.GetString("LblMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt möte.
        /// </summary>
        public static string LblNewEvent {
            get {
                return ResourceManager.GetString("LblNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se inlägg.
        /// </summary>
        public static string LblOpenPost {
            get {
                return ResourceManager.GetString("LblOpenPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        public static string LblPassword {
            get {
                return ResourceManager.GetString("LblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrera.
        /// </summary>
        public static string LblRegister {
            get {
                return ResourceManager.GetString("LblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forskning.
        /// </summary>
        public static string LblResearch {
            get {
                return ResourceManager.GetString("LblResearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string LblSave {
            get {
                return ResourceManager.GetString("LblSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa.
        /// </summary>
        public static string LblShow {
            get {
                return ResourceManager.GetString("LblShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idag.
        /// </summary>
        public static string LblToday {
            get {
                return ResourceManager.GetString("LblToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vecka.
        /// </summary>
        public static string LblWeek {
            get {
                return ResourceManager.GetString("LblWeek", resourceCulture);
            }
        }
    }
}
